[package]
name = "backend"
version = "0.1.0"
authors = ["Freyr <sky_rider_93@mail.ru>"]

[dependencies]
libc = ""
glib = "0.5"
glib-sys = "0.6"
gobject-sys = "0.6"
gstreamer = "0.11"
gstreamer-sys = "0.5"
gstreamer-video = "0.11"
gstreamer-mpegts-sys = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rmp-serde = "0.13.7"
zmq = "0.8"
log = "0.4"