#!/bin/bash

PROC=$@

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit 0
fi

IN=/tmp/testin
OUT=/tmp/testout

if [[ ! -p $IN ]]; then
    mkfifo $IN
fi

if [[ ! -p $OUT ]]; then
    mkfifo $OUT
fi

$PROC < $IN 1> $OUT &
PID=$!

trap "kill $PID 2> /dev/null" EXIT

function test {
    printf "\nVal:\n%s\nResult:\n%s\n" $1 $2
    #diff <(echo "$foo") <(echo "$bar")
}

DEFAULT="{\"graph\":\"play\"}"

echo "$DEFAULT" > $IN
read RES < $OUT

test $DEFAULT $RES
